require('dotenv').config();
const url     = require('url');
const express = require('express');
const path    = require('path');
const PORT    = process.env.PORT || 8000;
const queries = require('./public/javascript/queries.js');
const app     = express();

app.use(express.static(path.join(__dirname, 'public')));
app.set('views', path.join(__dirname, 'views'));
app.set('view engine', 'ejs');
app.get('/', (req, res) => res.render('pages/forum',{title: "Sign In"}));
app.get('/getTopics', queries.getTopics);
app.get('/userComments', (req,res) => res.render('pages/userComments',{title: "My Comments"}));
app.get('/getComments', queries.getComments);
app.get('/userID', queries.userID);
app.get('/authenticate',queries.authenticate);
app.get('/addTopic', queries.addTopic);
app.get('/addComment',queries.addComment);
app.get('/deleteTopic', queries.deleteTopic);
app.get('/deleteComment',queries.deleteComment);
app.get('/getTopicCreator',queries.getTopicCreator);
app.listen(PORT,()=> console.log(`Listening on port ${PORT}`));